services:
  apigateway:
    build: ./apigateway
    environment:
      - ENV=${ENV}
      - JWTSECRET=${JWTSECRET}
    volumes:
      - ./apigateway/src:/usr/src/app/src
      - ./apigateway/nodemon.json:/usr/src/app/nodemon.json
      - ./protos:/usr/src/app/protos
    ports:
      - 3000:8000

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 8080:15672
      - 5672:5672

  users:
    build: ./services/users
    environment:
      - ENV=${ENV}
      - JWTSECRET=${JWTSECRET}
      - JWTEXPIRE=1d
    volumes:
      - ./services/users/src:/usr/src/app/src
      - ./services/users/nodemon.json:/usr/src/app/nodemon.json
      - ./protos:/usr/src/app/protos
    ports:
      - 8000:8000
  users-database:
    build: ./database/users
    ports:
      - 5000:5432

  profile:
    build: ./services/profile
    environment:
      - ENV=${ENV}
      - JWTSECRET=${JWTSECRET}
    volumes:
      - ./services/profile/src:/usr/src/app/src
      - ./services/profile/nodemon.json:/usr/src/app/nodemon.json
      - ./protos:/usr/src/app/protos
    ports:
      - 8001:8000
  profile-database:
    build: ./database/profile
    ports: 
      - 5001:5432

  follows:
    build: ./services/follows
    environment:
      - ENV=${ENV}
      - JWTSECRET=${JWTSECRET}
    volumes:
      - ./services/follows/src:/usr/src/app/src
      - ./services/follows/nodemon.json:/usr/src/app/nodemon.json
      - ./protos:/usr/src/app/protos
    ports:
      - 8002:8000
  follows-database:
    build: ./database/follows
    ports: 
      - 5002:5432

  posts:
    build: ./services/posts
    environment:
      - ENV=${ENV}
      - JWTSECRET=${JWTSECRET}
    hostname: posts
    volumes:
      - ./services/posts/src:/usr/src/app/src
      - ./services/posts/nodemon.json:/usr/src/app/nodemon.json
      - ./protos:/usr/src/app/protos
    ports:
      - 8003:8000
  posts-worker:
    build: ./services/posts-worker
    environment:
      - ENV=${ENV}
      - JWTSECRET=${JWTSECRET}
    volumes:
      - ./services/posts-worker/src:/usr/src/app/src
      - ./services/posts-worker/nodemon.json:/usr/src/app/nodemon.json
      - ./protos:/usr/src/app/protos
  posts-database:
    build: ./database/posts
    ports: 
      - 5003:5432
  posts-redis:
    image: "redis:alpine"
    command: redis-server --requirepass redis
    ports:
     - 6000:6379
  
  comments:
    build: ./services/comments
    environment:
      - ENV=${ENV}
      - JWTSECRET=${JWTSECRET}
    volumes:
      - ./services/comments/src:/usr/src/app/src
      - ./services/comments/nodemon.json:/usr/src/app/nodemon.json
      - ./protos:/usr/src/app/protos
    ports:
      - 8004:8000
  comments-database:
    build: ./database/comments
    ports: 
      - 5004:5432
  comments-redis:
    image: "redis:alpine"
    command: redis-server --requirepass redis
    ports:
     - 6001:6379